### ISSUE TITLE
Generalizing GUI

### ISSUE THREAD

**Issue by genekogan** [mars-college/gpt3-sandbox#1]
This repo sets up a server-client for interacting with GPT-3. It does everything we need, but I'd like to strip down the interface to reveal more of the parameters you can use with GPT-3. So right now it looks like this:

<img width="390" alt="Screen Shot 2020-11-23 at 12 38 08 PM" src="https://user-images.githubusercontent.com/1335251/100013138-33565f00-2d89-11eb-8c1e-39ab8f15d787.png">

I want to remove the "examples" bit and add all the interface elements that you see on OpenAI's playground:

<img width="860" alt="Screen Shot 2020-11-23 at 12 42 39 PM" src="https://user-images.githubusercontent.com/1335251/100013275-6bf63880-2d89-11eb-810b-0d0cb26cb868.png">

So we'd add these sliders: response length, temperature, frequency penalty, presence penalty (all of them are floats between 0 and 1 except response length which we'd bound from 0 to say 500). The other element to add is "stop sequences" which is a list of strings the user can add (we can do this simple and make it a comma-separated list in a single text box, i can parse it when it gets submitted). The other stuff (presets, inject text, etc) is a bit trickier and we can think about adding later, but for now, these are the important bits. 

The React GUI is setup in `src/App.js`. Besides or the GUI elements, we need to pass their values to `handleClick(e)` (I think) which grabs the text body and sends it to the server. If we get those values along with the prompt to the python server, we should be good to go.

cc @lazaruslarue

**Comment by frclba** [comment]
Hi @genekogan I want to work on this.

**Comment by genekogan** [comment]
@fernand0aguilar great! although i talked with jesse and we decided not to use this but to instead build it from scratch. i'm going to start this asap and will update on the discord.
